/**
 * A curated set of expense-relevant emoji — deliberately NOT a full picker.
 * ~60 recognisable options cover real spending and fit on one thumb-scroll;
 * a complete Unicode picker would be a dependency, a search box and a lot of
 * scrolling for a purely decorative field.
 *
 * Each entry carries a name so the emoji is never the only semantic identifier
 * (screen readers announce "Groceries", not "cart emoji").
 */
export const CURATED_EMOJI: { emoji: string; name: string }[] = [
  { emoji: "🍔", name: "Burger" },
  { emoji: "🍛", name: "Meal" },
  { emoji: "🛒", name: "Groceries" },
  { emoji: "☕", name: "Coffee" },
  { emoji: "🥡", name: "Takeaway" },
  { emoji: "🍕", name: "Pizza" },
  { emoji: "🍽️", name: "Dining" },
  { emoji: "🍺", name: "Drinks" },
  { emoji: "🚗", name: "Car" },
  { emoji: "⛽", name: "Fuel" },
  { emoji: "🚕", name: "Taxi" },
  { emoji: "🚌", name: "Bus" },
  { emoji: "🚆", name: "Train" },
  { emoji: "🅿️", name: "Parking" },
  { emoji: "🔧", name: "Repairs" },
  { emoji: "🏠", name: "Home" },
  { emoji: "💡", name: "Electricity" },
  { emoji: "💧", name: "Water" },
  { emoji: "🌐", name: "Internet" },
  { emoji: "🛋️", name: "Furniture" },
  { emoji: "🧹", name: "Cleaning" },
  { emoji: "🔑", name: "Rent" },
  { emoji: "🛍️", name: "Shopping" },
  { emoji: "👕", name: "Clothing" },
  { emoji: "👟", name: "Shoes" },
  { emoji: "📱", name: "Mobile" },
  { emoji: "💻", name: "Computer" },
  { emoji: "🎁", name: "Gifts" },
  { emoji: "💊", name: "Medicine" },
  { emoji: "🏥", name: "Hospital" },
  { emoji: "🦷", name: "Dental" },
  { emoji: "🏋️", name: "Fitness" },
  { emoji: "🧴", name: "Personal care" },
  { emoji: "💇", name: "Salon" },
  { emoji: "🎓", name: "Education" },
  { emoji: "📚", name: "Books" },
  { emoji: "🏫", name: "School" },
  { emoji: "✏️", name: "Stationery" },
  { emoji: "🎬", name: "Movies" },
  { emoji: "🎮", name: "Gaming" },
  { emoji: "🎵", name: "Music" },
  { emoji: "📺", name: "Streaming" },
  { emoji: "🎨", name: "Hobbies" },
  { emoji: "⚽", name: "Sports" },
  { emoji: "💰", name: "Money" },
  { emoji: "🏦", name: "Bank" },
  { emoji: "💳", name: "Card" },
  { emoji: "📈", name: "Investments" },
  { emoji: "💸", name: "Money sent" },
  { emoji: "🧾", name: "Bills" },
  { emoji: "✈️", name: "Flights" },
  { emoji: "🏨", name: "Hotels" },
  { emoji: "🏖️", name: "Holiday" },
  { emoji: "🧳", name: "Travel" },
  { emoji: "👨‍👩‍👧", name: "Family" },
  { emoji: "👶", name: "Children" },
  { emoji: "🐕", name: "Pets" },
  { emoji: "🌱", name: "Garden" },
  { emoji: "📦", name: "Subscriptions" },
  { emoji: "☁️", name: "Cloud storage" },
  { emoji: "🛡️", name: "Insurance" },
  { emoji: "🙏", name: "Donations" },
  { emoji: "🎉", name: "Celebrations" },
  { emoji: "📌", name: "Other" },
];
