import type { CatalogRoute } from "./helpers";

/** Every Worker API route we currently expose. Used by the contract matrix. */
export const CATALOG_ROUTES: CatalogRoute[] = [
  { module: "health", method: "GET", path: "/api/health", auth: "public" },

  { module: "auth", method: "GET", path: "/api/auth/me", auth: "public" },
  { module: "auth", method: "GET", path: "/api/auth/google/status", auth: "required" },
  { module: "auth", method: "GET", path: "/api/auth/google/start", auth: "public" },
  { module: "auth", method: "GET", path: "/api/auth/google/callback", auth: "public" },
  { module: "auth", method: "POST", path: "/api/auth/logout", auth: "public", mutation: true },

  { module: "families", method: "GET", path: "/api/families", auth: "required" },
  { module: "families", method: "POST", path: "/api/families", auth: "required", mutation: true },
  { module: "families", method: "GET", path: "/api/families/me/members", auth: "required" },
  { module: "families", method: "GET", path: "/api/families/me/dashboard-stats", auth: "required" },
  { module: "families", method: "GET", path: "/api/families/me/activity", auth: "required" },
  { module: "families", method: "POST", path: "/api/families/invites/tok/accept", auth: "required", mutation: true },
  { module: "families", method: "GET", path: "/api/families/fam-1", auth: "required" },
  { module: "families", method: "PATCH", path: "/api/families/fam-1", auth: "required", mutation: true },
  { module: "families", method: "GET", path: "/api/families/fam-1/members", auth: "required" },
  { module: "families", method: "PATCH", path: "/api/families/fam-1/members/mem-1", auth: "required", mutation: true },
  { module: "families", method: "POST", path: "/api/families/fam-1/invites", auth: "required", mutation: true },
  { module: "families", method: "GET", path: "/api/families/fam-1/activity", auth: "required" },

  { module: "documents", method: "GET", path: "/api/documents", auth: "required" },
  { module: "documents", method: "POST", path: "/api/documents", auth: "required", mutation: true },
  { module: "documents", method: "GET", path: "/api/documents/doc-1", auth: "required" },
  { module: "documents", method: "PATCH", path: "/api/documents/doc-1", auth: "required", mutation: true },
  { module: "documents", method: "DELETE", path: "/api/documents/doc-1", auth: "required", mutation: true },
  { module: "documents", method: "POST", path: "/api/documents/doc-1/files/upload", auth: "required", mutation: true },
  { module: "documents", method: "POST", path: "/api/documents/doc-1/files/upload-url", auth: "required", mutation: true },
  { module: "documents", method: "POST", path: "/api/documents/doc-1/files", auth: "required", mutation: true },
  { module: "documents", method: "GET", path: "/api/documents/doc-1/files", auth: "required" },
  { module: "documents", method: "GET", path: "/api/documents/doc-1/files/fid-1/download", auth: "required" },
  { module: "documents", method: "GET", path: "/api/documents/doc-1/comments", auth: "required" },
  { module: "documents", method: "POST", path: "/api/documents/doc-1/comments", auth: "required", mutation: true },
  { module: "documents", method: "DELETE", path: "/api/documents/doc-1/comments/c-1", auth: "required", mutation: true },

  { module: "events", method: "GET", path: "/api/events", auth: "required" },
  { module: "events", method: "POST", path: "/api/events", auth: "required", mutation: true },
  { module: "events", method: "GET", path: "/api/events/evt-1", auth: "required" },
  { module: "events", method: "PATCH", path: "/api/events/evt-1", auth: "required", mutation: true },
  { module: "events", method: "DELETE", path: "/api/events/evt-1", auth: "required", mutation: true },
  { module: "events", method: "POST", path: "/api/events/evt-1/cancel", auth: "required", mutation: true },
  { module: "events", method: "POST", path: "/api/events/evt-1/attendees", auth: "required", mutation: true },
  { module: "events", method: "DELETE", path: "/api/events/evt-1/attendees/mem-1", auth: "required", mutation: true },

  { module: "calendar", method: "POST", path: "/api/calendar/feed-token", auth: "required", mutation: true },
  { module: "calendar", method: "GET", path: "/api/calendar/feed-token", auth: "required" },
  { module: "calendar", method: "GET", path: "/api/calendar/feed/nope.ics", auth: "public" },
  { module: "calendar", method: "GET", path: "/api/calendar/events/evt-1/ics", auth: "required" },

  { module: "church", method: "GET", path: "/api/church/snapshot", auth: "required" },
  { module: "church", method: "POST", path: "/api/church/settle", auth: "required", mutation: true },

  { module: "tasks", method: "GET", path: "/api/tasks", auth: "required" },
  { module: "tasks", method: "POST", path: "/api/tasks", auth: "required", mutation: true },
  { module: "tasks", method: "GET", path: "/api/tasks/t-1", auth: "required" },
  { module: "tasks", method: "PATCH", path: "/api/tasks/t-1", auth: "required", mutation: true },
  { module: "tasks", method: "DELETE", path: "/api/tasks/t-1", auth: "required", mutation: true },

  { module: "contacts", method: "GET", path: "/api/contacts", auth: "required" },
  { module: "contacts", method: "GET", path: "/api/contacts/google-status", auth: "required" },
  { module: "contacts", method: "POST", path: "/api/contacts/sync", auth: "required", mutation: true },
  { module: "contacts", method: "POST", path: "/api/contacts", auth: "required", mutation: true },
  { module: "contacts", method: "GET", path: "/api/contacts/c-1", auth: "required" },
  { module: "contacts", method: "PATCH", path: "/api/contacts/c-1", auth: "required", mutation: true },
  { module: "contacts", method: "DELETE", path: "/api/contacts/c-1", auth: "required", mutation: true },

  { module: "notifications", method: "GET", path: "/api/notifications", auth: "required" },
  { module: "notifications", method: "POST", path: "/api/notifications/read-all", auth: "required", mutation: true },
  { module: "notifications", method: "POST", path: "/api/notifications/n-1/read", auth: "required", mutation: true },
  { module: "notifications", method: "GET", path: "/api/notifications/prefs", auth: "required" },
  { module: "notifications", method: "PUT", path: "/api/notifications/prefs", auth: "required", mutation: true },
  { module: "notifications", method: "POST", path: "/api/notifications/test-email", auth: "required", mutation: true },

  { module: "expenses", method: "GET", path: "/api/expenses/categories", auth: "required" },
  { module: "expenses", method: "POST", path: "/api/expenses/categories", auth: "required", mutation: true },
  { module: "expenses", method: "POST", path: "/api/expenses/categories/cat-1/archive", auth: "required", mutation: true },
  { module: "expenses", method: "GET", path: "/api/expenses", auth: "required" },
  { module: "expenses", method: "GET", path: "/api/expenses/suggestions", auth: "required" },
  { module: "expenses", method: "POST", path: "/api/expenses", auth: "required", mutation: true },
  { module: "expenses", method: "GET", path: "/api/expenses/summary", auth: "required" },
  { module: "expenses", method: "GET", path: "/api/expenses/e-1", auth: "required" },
  { module: "expenses", method: "PATCH", path: "/api/expenses/e-1", auth: "required", mutation: true },
  { module: "expenses", method: "DELETE", path: "/api/expenses/e-1", auth: "required", mutation: true },

  { module: "finance", method: "GET", path: "/api/finance/settings", auth: "required" },
  { module: "finance", method: "PUT", path: "/api/finance/settings", auth: "required", mutation: true },
  { module: "finance", method: "GET", path: "/api/finance/incomes", auth: "required" },
  { module: "finance", method: "POST", path: "/api/finance/incomes", auth: "required", mutation: true },
  { module: "finance", method: "PATCH", path: "/api/finance/incomes/i-1", auth: "required", mutation: true },
  { module: "finance", method: "DELETE", path: "/api/finance/incomes/i-1", auth: "required", mutation: true },
  { module: "finance", method: "GET", path: "/api/finance/commitments", auth: "required" },
  { module: "finance", method: "POST", path: "/api/finance/commitments", auth: "required", mutation: true },
  { module: "finance", method: "PATCH", path: "/api/finance/commitments/c-1", auth: "required", mutation: true },
  { module: "finance", method: "DELETE", path: "/api/finance/commitments/c-1", auth: "required", mutation: true },
  { module: "finance", method: "POST", path: "/api/finance/commitments/c-1/pay", auth: "required", mutation: true },
  { module: "finance", method: "GET", path: "/api/finance/overview", auth: "required" },

  { module: "funds", method: "GET", path: "/api/funds", auth: "required" },
  { module: "funds", method: "POST", path: "/api/funds", auth: "required", mutation: true },
  { module: "funds", method: "GET", path: "/api/funds/f-1", auth: "required" },
  { module: "funds", method: "GET", path: "/api/funds/f-1/contributions", auth: "required" },
  { module: "funds", method: "POST", path: "/api/funds/f-1/contributions", auth: "required", mutation: true },
  { module: "funds", method: "GET", path: "/api/funds/f-1/spends", auth: "required" },
  { module: "funds", method: "POST", path: "/api/funds/f-1/spends", auth: "required", mutation: true },
  { module: "funds", method: "POST", path: "/api/funds/f-1/settle", auth: "required", mutation: true },
  { module: "funds", method: "GET", path: "/api/funds/f-1/activity", auth: "required" },

  { module: "wishlist", method: "GET", path: "/api/wishlist", auth: "required" },
  { module: "wishlist", method: "POST", path: "/api/wishlist", auth: "required", mutation: true },
  { module: "wishlist", method: "GET", path: "/api/wishlist/w-1", auth: "required" },
  { module: "wishlist", method: "PATCH", path: "/api/wishlist/w-1", auth: "required", mutation: true },
  { module: "wishlist", method: "DELETE", path: "/api/wishlist/w-1", auth: "required", mutation: true },

  { module: "items", method: "GET", path: "/api/items", auth: "required" },
  { module: "items", method: "POST", path: "/api/items", auth: "required", mutation: true },
  { module: "items", method: "GET", path: "/api/items/i-1", auth: "required" },
  { module: "items", method: "PATCH", path: "/api/items/i-1", auth: "required", mutation: true },
  { module: "items", method: "DELETE", path: "/api/items/i-1", auth: "required", mutation: true },

  { module: "vault", method: "POST", path: "/api/vault/init", auth: "required", mutation: true },
  { module: "vault", method: "GET", path: "/api/vault/status", auth: "required" },
  { module: "vault", method: "GET", path: "/api/vault/keys", auth: "required" },
  { module: "vault", method: "PUT", path: "/api/vault/keys", auth: "required", mutation: true },
  { module: "vault", method: "GET", path: "/api/vault/member-keys", auth: "required" },
  { module: "vault", method: "PUT", path: "/api/vault/member-keys", auth: "required", mutation: true },
  { module: "vault", method: "GET", path: "/api/vault/items", auth: "required" },
  { module: "vault", method: "POST", path: "/api/vault/items", auth: "required", mutation: true },
  { module: "vault", method: "GET", path: "/api/vault/items/v-1", auth: "required" },
  { module: "vault", method: "POST", path: "/api/vault/items/v-1/reveal", auth: "required", mutation: true },
  { module: "vault", method: "PATCH", path: "/api/vault/items/v-1", auth: "required", mutation: true },
  { module: "vault", method: "DELETE", path: "/api/vault/items/v-1", auth: "required", mutation: true },
  { module: "vault", method: "POST", path: "/api/vault/items/v-1/tags", auth: "required", mutation: true },
  { module: "vault", method: "GET", path: "/api/vault/search", auth: "required" },
  { module: "vault", method: "POST", path: "/api/vault/passkeys/register/start", auth: "required", mutation: true },
  { module: "vault", method: "POST", path: "/api/vault/passkeys/register/finish", auth: "required", mutation: true },
  { module: "vault", method: "POST", path: "/api/vault/passkeys/authenticate/start", auth: "required", mutation: true },
  { module: "vault", method: "POST", path: "/api/vault/passkeys/authenticate/finish", auth: "required", mutation: true },

  { module: "activity", method: "GET", path: "/api/activity/me", auth: "required" },

  { module: "assistant", method: "POST", path: "/api/assistant/chat", auth: "required", mutation: true },
  { module: "assistant", method: "GET", path: "/api/assistant/status", auth: "required" },

  { module: "admin", method: "GET", path: "/api/admin/storage", auth: "required" },
  { module: "admin", method: "POST", path: "/api/admin/storage/connect/start", auth: "required", mutation: true },
  { module: "admin", method: "GET", path: "/api/admin/storage/connect/callback", auth: "required" },
  { module: "admin", method: "GET", path: "/api/admin/storage/stats", auth: "required" },
  { module: "admin", method: "POST", path: "/api/admin/storage/disconnect", auth: "required", mutation: true },
  { module: "admin", method: "GET", path: "/api/admin/metrics", auth: "required" },

  { module: "device-lock", method: "GET", path: "/api/device-lock/status", auth: "required" },
  { module: "device-lock", method: "POST", path: "/api/device-lock/webauthn/options", auth: "required", mutation: true },
  { module: "device-lock", method: "POST", path: "/api/device-lock/webauthn/register", auth: "required", mutation: true },
  { module: "device-lock", method: "POST", path: "/api/device-lock/webauthn/assert", auth: "required", mutation: true },
  { module: "device-lock", method: "POST", path: "/api/device-lock/pin/setup", auth: "required", mutation: true },
  { module: "device-lock", method: "POST", path: "/api/device-lock/pin/verify", auth: "required", mutation: true },
];
